### ISSUE TITLE
Project improvements tracking

### ISSUE THREAD

**Issue by luiztauffer** [mikarubi/voluseg#21]
Overview tracking of latest features and bug fixes:

- [x] Black formatting  #16 
- [x] Containerize
  - [x] Docker basics  #17 
  - [x] #35 
  - [x] action auto-build and publish to GHCR 
- [x] #23 
- [x] Add tests #14 
- [x] Improve docstrings, typing and imports #19 
- [x] #29 
- [x] #22 
- [x] #18 
- [ ] NWB interface
  - [x] read from local file #30 
  - [x] read from remote file #30 
  - [x] save results to NWB format #43
  - [ ] https://github.com/mikarubi/voluseg/issues/50
- [ ] Python package
  - [x] #45  
  - [ ] release to PyPI
- [x] Cloud IaC
  - [x] https://github.com/mikarubi/voluseg/pull/46
- [ ] Documentation
  - [ ] https://github.com/mikarubi/voluseg/pull/48
  - [ ] action to auto-build and publish documentation
- [ ] #36 
- [ ] #9
